export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE'

export const FETCH_CHATS_REQUEST = 'FETCH_CHATS_REQUEST'
export const FETCH_CHATS_SUCCESS = 'FETCH_CHATS_SUCCESS'
export const FETCH_CHATS_FAILURE = 'FETCH_CHATS_FAILURE'